### PR TITLE
Restart katuma_reports_unicorn after deploy

### PR DESCRIPTION
**Pull request by sauloperez**
Otherwise the code changes are not loaded

### CODE REVIEW

**Comment by sauloperez** [comment]
It fails :see_no_evil: but it's not the first time I see this:

```shell
TASK [vendor/carlosbuenosvinos.ansistrano-deploy : Restart katuma_reports_unicorn] *********************************************************
Tuesday 17 October 2017  16:12:06 +0200 (0:01:09.888)       0:05:09.603 *******
fatal: [staging.katuma.org]: FAILED! => {"changed": true, "cmd": ["systemctl", "restart", "katuma_reports_unicorn.service"], "delta": "0:00:00.014878", "end": "2017-10-17 14:12:07.994113", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2017-10-17 14:12:07.979235", "stderr": "Failed to restart katuma_reports_unicorn.service: The name org.freedesktop.PolicyKit1 was not provided by any .service files\nSee system logs and 'systemctl status katuma_reports_unicorn.service' for details.", "stderr_lines": ["Failed to restart katuma_reports_unicorn.service: The name org.freedesktop.PolicyKit1 was not provided by any .service files", "See system logs and 'systemctl status katuma_reports_unicorn.service' for details."], "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/home/pau/dev/katuma-provisioning/deploy.retry
```

**Comment by enricostano** [comment]
@sauloperez `become: yes`

**Comment by sauloperez** [comment]
Make sure we do #10 first

**Comment by sauloperez** [comment]
We never update this app so we can live without a restart. We got way more important things to do.

**Pull request closed without merging**
